import { Injectable, inject } from '@angular/core';
import { Share, ShareOptions } from '@capacitor/share';
import { LoggerService } from './logger.service';
import { ToastService } from './toast.service';
import { DetectedEntity } from '../types';

/**
 * Share functionality service
 * Allows sharing detections and app data
 */
@Injectable({
  providedIn: 'root'
})
export class ShareService {
  private logger = inject(LoggerService);
  private toast = inject(ToastService);

  /**
   * Check if sharing is supported
   */
  async canShare(): Promise<boolean> {
    try {
      const result = await Share.canShare();
      return result.value;
    } catch {
      return false;
    }
  }

  /**
   * Share an entity detection
   */
  async shareEntity(entity: DetectedEntity): Promise<void> {
    const text = this.formatEntityForSharing(entity);

    await this.share({
      title: `Paranormal Detection: ${entity.name}`,
      text,
      dialogTitle: 'Share Detection'
    });
  }

  /**
   * Share multiple entities
   */
  async shareMultipleEntities(entities: DetectedEntity[]): Promise<void> {
    const text = this.formatMultipleEntitiesForSharing(entities);

    await this.share({
      title: 'Necrometer Detection Report',
      text,
      dialogTitle: 'Share Report'
    });
  }

  /**
   * Share app with friends
   */
  async shareApp(): Promise<void> {
    await this.share({
      title: 'Check out Necrometer!',
      text: 'I\'ve been using Necrometer to detect paranormal activity. Try it yourself!',
      url: 'https://your-app-url.com', // TODO: Update with actual URL
      dialogTitle: 'Share Necrometer'
    });
  }

  /**
   * Generic share method
   */
  private async share(options: ShareOptions): Promise<void> {
    try {
      await Share.share(options);
      this.logger.info('Content shared successfully');
      this.toast.success('Shared successfully');
    } catch (error: unknown) {
      // User cancelled share
      const errorMessage = error instanceof Error ? error.message : String(error);
      if (errorMessage.includes('cancel')) {
        this.logger.debug('Share cancelled by user');
        return;
      }

      this.logger.error('Failed to share', error);
      this.toast.error('Failed to share. Please try again.');
    }
  }

  /**
   * Format entity for sharing
   */
  private formatEntityForSharing(entity: DetectedEntity): string {
    const date = new Date(entity.timestamp).toLocaleString();

    return `
👻 PARANORMAL DETECTION REPORT

Entity: ${entity.name}
Type: ${entity.type}
Detected: ${date}
EMF Reading: ${entity.emfReading.toFixed(2)} mG
Instability: ${entity.instability}%
Status: ${entity.contained ? 'Contained' : 'Active'}

Backstory:
${entity.backstory}

---
Detected using Necrometer
    `.trim();
  }

  /**
   * Format multiple entities for sharing
   */
  private formatMultipleEntitiesForSharing(entities: DetectedEntity[]): string {
    const header = `
👻 PARANORMAL INVESTIGATION REPORT
Total Detections: ${entities.length}
Contained: ${entities.filter(e => e.contained).length}
Active: ${entities.filter(e => !e.contained).length}

---

DETECTIONS:
    `.trim();

    const entitySummaries = entities.map((entity, index) => {
      const date = new Date(entity.timestamp).toLocaleString();
      return `
${index + 1}. ${entity.name} (${entity.type})
   Detected: ${date}
   EMF: ${entity.emfReading.toFixed(2)} mG
   Status: ${entity.contained ? 'Contained' : 'Active'}
      `.trim();
    }).join('\n\n');

    return `${header}\n\n${entitySummaries}\n\n---\nGenerated by Necrometer`;
  }
}
